- name: Deploy on openstack
  gather_facts: false
  hosts: localhost
  tasks:
    - name: create vm
      os_server:
       state: present
       name: webserver
       image: Ubuntu 18.04 (Bionic) (user:ubuntu) 
       key_name: priv
       availability_zone: compute-5-6-7-8
       wait: yes
       flavor: 2-2-10
       auto_floating_ip: yes
       network: web-server
       wait: yes
      register: my_vm
    - name: add vm to invetory
      add_host:
       name: openstack_vm
       groups: web
       ansible_host: "{{ my_vm.server.public_v4 }}"
       ansible_user: ubuntu
       ansible_ssh_host: "{{ my_vm.server.public_v4 }}"  
    - name: wait for ssh
      pause:
       seconds: 30
